default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_notes_development

test:
  <<: *default
  database: my_notes_test

production:
  <<: *default
  database: my_notes_production
  username: my_notes
  password: <%= ENV['RAILS_BASE_DATABASE_PASSWORD'] %>
